import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed inset-0 -z-10 bg-gradient-to-b from-[#FFD700]/15 via-[#FFCC00]/10 to-transparent blur-2xl pointer-events-none h-[200px] w-[600px] left-1/2 -translate-x-1/2" />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
